# Generated by Django 4.2.5 on 2023-09-09 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usermodels_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodels',
            name='external_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='usermodels',
            name='phone',
            field=models.PositiveIntegerField(verbose_name='Номер телефона'),
        ),
        migrations.CreateModel(
            name='UserMessageModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1024)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usermodels')),
            ],
        ),
    ]
